### ISSUE TITLE
Issues with opening files in ``/tmp``

### ISSUE THREAD

**Issue by kozross** [owickstrom/neovim-ghci#12]
I get this error a lot in my terminal after I close Neovim:

    E482: Can't open file /tmp/nvimsezOa8/1 for writing: no such file or directory

The exact file name varies, but the error is consistent.

**Comment by owickstrom** [comment]
Thanks for reporting. There is a hook that cleans up when Neovim is closed, seems like there is some state mismatch going on.

Also, this issue in the upstream project "intero-neovim" suggests its related to the Neomake maker: https://github.com/parsonsmatt/intero-neovim/issues/67#issuecomment-317085659

I'm currently working on support for using any GHCi in `intero-neovim`, so that we don't need this fork anymore (and all the duplicate issues!) I'd prefer waiting to investigating this issue until that PR is merged, and we can see if it is a problem also in `intero-neovim`. Sorry for the mess with forks and "unforking".

**Comment by owickstrom** [comment]
Hi! I'm deprecating this project in favor of its upstream, `intero-neovim`, which now [has support for using any GHCi backend](https://github.com/parsonsmatt/intero-neovim#using-a-custom-backend). The issue tracker will be closed, but the repository will stay for a while until people have had time to migrate away. If you're experiencing the same issue with intero-neovim, please repost the issue there. Thank you!
